### ISSUE TITLE
Great preview utility - but no keybinding and preview window doesn't resize!

### ISSUE THREAD

**Issue by objectkit** [Raynes/coffeefilter#6]
Really happy to have this to hand for previewing potentially troublesome coffeescript, but I found the preview window does not scroll, so I have to minimise text to see all output... and I can't seem to find a way to set a keybinding for the Strain command. Poss to update to bind keybinding for the strain command? And make the preview window scrollable? Cheers!

**Comment by Raynes** [comment]
You can bind it to anything using Atom's configuration, but I should
definitely provide defaults. As for scrolling, it should definitely allow
scrolling. Guessing a recent Atom change broke that. I'll take a look!
Thanks for the heads up!

**Comment by objectkit** [comment]
NP! Its a great utility @Raynes - glad to have it:) 

If its any help, in relation to Atom 1.2.4 keybinding configuration, typing "strain" doesn't return a result, and "coffeefilter" just shows the core:cancel command for source Coffeefilter bound to escape (which works fine)
